language: python

matrix:
  include:
    - python: 2.7
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true

services:
  - xvfb

before_install:
    # Tricks to avoid matplotlib error about X11:
    # 'no display name and no $DISPLAY environment variable'

    # enable gui, see https://docs.travis-ci.com/user/gui-and-headless-browsers
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
            export DISPLAY=:99.0;
            sh -e /etc/init.d/xvfb start;
            sleep 3;
      fi

# Installing matplotlib is long processes. Using a cache allows
# to fasten the tests by reducing drastically the install time.
cache:
    directories:
        # Cache for pip, mostly to speed up matplotlib install
        - $HOME/.cache/pip

install:
  - pip install ".[testing]"
  - pip install pytest-cov

script:
  - pytest --cov kmapper

after_success:
  - bash <(curl -s https://codecov.io/bash)
